[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/gracias"
  to = "/gracias/"
  status = 301

[[redirects]]
  from = "/portfolio"
  to = "/portfolio/"
  status = 301

[[redirects]]
  from = "/servicios"
  to = "/servicios/"
  status = 301
